*       params.
*       -------
*
      INCLUDE 'params.h'
      IMPLICIT REAL*8  (A-H,O-Z)
      REAL*8  MP,MP0,MPDOT
*
      INCLUDE 'mpi_base.h'
*
      COMMON/NAMES/  NTOT,NPAIRS,NTTOT,N,NNBMAX,NCRIT,NFIX,NMERGE,NSUB,
     &               IPHASE,IFIRST,ICOMP,JCOMP,ICLOSE,JCLOSE,JCMAX,
     &               KSPAIR,NRUN,MODEL,NC,NZERO,NBZERO,NBIN0,NHI0,
     &               NAME0,NCH,NCHAOS,IDUM1,KZ(50),NNBOPT,NIMBH,
     &               ITAIL0,NTAIL, !Tidal tail position indicators
     &               NEW2(5)

      COMMON/PARAMS/ ETAI,ETAR,DTADJ,DELTAT,TCRIT,QE,RBAR,ZMBAR,
     &               DTMIN,RMIN,ETAU,CMSEP2,ECLOSE,GMIN,GMAX,ETA0,
     &               TWOPI,ONE3,ONE6,ONE9,ONE12,TCR0,TRH,BODYM,BODY1,
     &               SMIN,RMIN2,RMIN22,STEPJ,ALPHA,ZNBMIN,ZNBMAX,EBH,
     &               TIME,TADJ,TNEXT,CPU,CPU0,CPUTOT,ZMASS,RSCALE,TCR,
     &               TRC,BE(3),CMR(4),CMRDOT(4),ZKIN,POT,EBIN,EBIN0,
     &               ESUB,EMERGE,ECOLL,EDISS,ESYNC,E(12),ERROR,ERRTOT,
     &               DETOT,ETCORR,AZ,PCRIT,EBCH0,RTIDE,TSCALE,TIDAL(4),
     &               HT,ETIDE,EGRAV,RSFAC,RSPH2,RC,RC2,RC2IN,VC,ZMC,
     &               RDENS(3),RHOD,RHOM,RSMIN,RMAX,DMIN1,DMIN2,DMIN3,
     &               DMIN4,DMINC,SBCOLL,BBCOLL,CHCOLL,DELTAS,ORBITS(9),
     &               GPRINT(9),TLASTT,TLASTS,TLASTB(9),TDUMP,
     &               SCOEFF(12),TOFF,TTOT,EBESC,EMESC,ESESC,CLIGHT,
     &               RZ,TINY,SMAX,WTOT,WTOT0,TCRITP,ZSMASS0,ZBMASS0,
     &               BIMBH,DTBH,DUMMY(93)