    SUBROUTINE POINTALLO(NALL1)

    INTEGER :: NALL1,NALL,LALL,KALL

    USE POINTERS

!     set the list length in multiples of 4096

    NALL = (INT(NALL1/4096)+1)*4096
    KALL = NALL/4
    LALL = 600


!     allocate nbody common variables

    ALLOCATE(X(3,NALL))
    ALLOCATE(XDOT(3,NALL))
    ALLOCATE(X0(3,NALL))
    ALLOCATE(X0DOT(3,NALL))
    ALLOCATE(F(3,NALL))
    ALLOCATE(FDOT(3,NALL))
    ALLOCATE(BODY(NALL))
    ALLOCATE(RS(NALL))
    ALLOCATE(FI(3,NALL))
    ALLOCATE(D1(3,NALL))
    ALLOCATE(D2(3,NALL))
    ALLOCATE(D3(3,NALL))
    ALLOCATE(FR(3,NALL))
    ALLOCATE(D1R(3,NALL))
    ALLOCATE(D2R(3,NALL))
    ALLOCATE(D3R(3,NALL))
    ALLOCATE(STEP(NALL))
    ALLOCATE(T0(NALL))
    ALLOCATE(STEPR(NALL))
    ALLOCATE(T0R(NALL))
    ALLOCATE(TIMENW(NALL))
    ALLOCATE(RADIUS(NALL))
    ALLOCATE(TEV(NALL))
    ALLOCATE(TEV0(NALL))
    ALLOCATE(BODY0(NALL))
    ALLOCATE(EPOCH(NALL))
    ALLOCATE(SPIN(NALL))
    ALLOCATE(XSTAR(NALL))
    ALLOCATE(ZLMSTY(NALL))
    ALLOCATE(FIDOT(3,NALL))
    ALLOCATE(D0(3,NALL))
    ALLOCATE(FRDOT(3,NALL))
    ALLOCATE(D0R(3,NALL))
    ALLOCATE(KSTAR(NALL))
    ALLOCATE(NAME(NALL))
    ALLOCATE(IMINR(NALL))
    ALLOCATE(LIST(LALL,NALL))
    ALLOCATE(FENZO(3,NALL))


!     allocate binary common variables

    ALLOCATE(U(4,KALL))
    ALLOCATE(U0(4,KALL))
    ALLOCATE(UDOT(4,KALL))
    ALLOCATE(FU(4,KALL))
    ALLOCATE(FUDOT(4,KALL))
    ALLOCATE(FUDOT2(4,KALL))
    ALLOCATE(FUDOT3(4,KALL))
    ALLOCATE(H(KALL))
    ALLOCATE(HDOT(KALL))
    ALLOCATE(HDOT2(KALL))
    ALLOCATE(HDOT3(KALL))
    ALLOCATE(HDOT4(KALL))
    ALLOCATE(DTAU(KALL))
    ALLOCATE(TDOT2(KALL))
    ALLOCATE(TDOT3(KALL))
    ALLOCATE(R(KALL))
    ALLOCATE(R0(KALL))
    ALLOCATE(GAMMA(KALL))
    ALLOCATE(SF(7,KALL))
    ALLOCATE(H0(KALL))
    ALLOCATE(FP0(4,KALL))
    ALLOCATE(FD0(4,KALL))
    ALLOCATE(KBLIST(10*KALL))
    ALLOCATE(KSLOW(KALL))
    ALLOCATE(TBLIST)


    END SUBROUTINE
