
extern "C" void FORTRAN_NAME(star_feedback1)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *temp, float *u, float *v,
		       float *w, float *dt, float *r, float *dx,
                       float *t, float *z,
             float *d1, float *x1, float *v1, float *t1,
             int *nmax, float *xstart, float *ystart, float *zstart,
     				 int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
             float *mp, float *tdp, float *tcp, float *te, float *ge,
		       int *idual);
extern "C" void FORTRAN_NAME(star_feedback2)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *te, float *ge, float *u, float *v,
		       float *w, float *metal,
             int *idual, int *imetal, int *imethod, float *dt,
		       float *r, float *dx, float *t, float *z,
             float *d1, float *x1, float *v1, float *t1,
                       float *sn_param, float *m_eject, float *yield,
	     int *distrad, int *diststep, int *distcells,
             int *nmax, float *xstart, float *ystart, float *zstart,
		       int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
	     float *mp, float *tdp, float *tcp, float *metalf, int *type,
	     float *justburn, int *crmodel, float *crfeedback, float *cr);
 
extern "C" void FORTRAN_NAME(star_feedback3mom)(int *nx, int *ny, int *nz,
						float *d, float *mu, float *dm, float *te, float *ge, float *u, float *v,
		       float *w, float *metal, float *zfield1, float *zfield2,
	     int *idual, int *imetal, int *imulti_metals, int *imethod, 
		       float *dt, float *r, float *dx, float *t, float *z,
             float *d1, float *x1, float *v1, float *t1,
                       float *sn_param, float *m_eject, float *yield,
             int *nmax, float *xstart, float *ystart, float *zstart,
		       int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
             float *mp, float *tdp, float *tcp, float *metalf, int *type,
	     float *justburn, float *kinf, float *exptime);

extern "C" void FORTRAN_NAME(star_feedback3)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *te, float *ge, float *u, float *v,
		       float *w, float *metal, float *zfield1, float *zfield2,
	     int *idual, int *imetal, int *imulti_metals, int *imethod, 
		       float *dt, float *r, float *dx, float *t, float *z,
             float *d1, float *x1, float *v1, float *t1,
                       float *sn_param, float *m_eject, float *yield,
	     int *distrad, int *diststep, int *distcells,
             int *nmax, float *xstart, float *ystart, float *zstart,
		       int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
             float *mp, float *tdp, float *tcp, float *metalf, int *type,
			float *justburn, int *crmodel, float *crfeedback, float *cr);

extern "C" void FORTRAN_NAME(star_feedback5)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *te, float *ge, float *u, float *v, 
		       float *w, float *metal,
             int *idual, int *imetal, int *imethod, float *dt, 
		       float *r, float *dx, float *t, float *z, 
             float *d1, float *x1, float *v1, float *t1, float *yield,
             int *nmax, float *xstart, float *ystart, float *zstart, 
		       int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
             float *mp, float *tdp, float *tcp, float *metalf, int *type);
 
extern "C" void FORTRAN_NAME(star_feedback4)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *te, float *ge, float *u, float *v, 
		       float *w, float *metal,
             int *idual, int *imetal, int *imethod, float *dt, 
		       float *r, float *dx, float *t, float *z, 
             float *d1, float *x1, float *v1, float *t1,
                       float *sn_param, float *m_eject, float *yield,
             int *nmax, float *xstart, float *ystart, float *zstart, 
		       int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
             float *mp, float *tdp, float *tcp, float *metalf, int *type);

extern "C" void FORTRAN_NAME(star_feedback_ssn)(
    int *nx, int *ny, int *nz,
    float *d, float *dm, float *te, float *ge, float *u, float *v, 
    float *w, float *metal,
    int *idual, int *imetal, int *imethod, float *dt, 
    float *r, float *dx, float *t, float *z, 
    float *d1, float *x1, float *v1, float *t1,
    float *yield,
    int *nmax, float *xstart, float *ystart, float *zstart, 
    int *ibuff, int *level,
    float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
    float *mp, float *tdp, float *tcp, float *metalf, int *type,
    int *explosionFlag, 
    float *smthresh, int *willExplode, float *soonestExplosion,
    float *mu,
    float *te1, float *metalIIfield, float *metalIIfrac, int *imetalII,
    float *s49_tot, int *maxlevel,
    int *distrad, int *diststep, int *distcells);

extern "C" void FORTRAN_NAME(star_feedback7)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *te, float *ge, float *u, float *v, 
		       float *w, float *metal,
             int *idual, int *imetal, int *imethod, float *dt, 
		       float *r, float *dx, float *t, float *z, 
             float *d1, float *x1, float *v1, float *t1,
                       float *sn_param, float *m_eject, float *yield,
             int *nmax, float *xstart, float *ystart, float *zstart, 
		       int *ibuff, int *level,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
	     float *mp, float *tdp, float *tcp, float *metalf, int *type,
			float *justburn, int *ctype, float *mbhradius);

/* adding distributed starmaker and feedback (from Norman+ 2014 and
   So+ 2014) */

extern "C" void FORTRAN_NAME(star_feedback10)(int *nx, int *ny, int *nz,
             float *d, float *dm, float *te, float *ge, float *u, float *v,
		       float *w, float *metal, float *zfield1, float *zfield2,
	     int *idual, int *imetal, int *imulti_metals, int *imethod, 
		       float *dt, float *r, float *dx, float *t, float *z,
             float *d1, float *x1, float *v1, float *t1,
                       float *sn_param, float *m_eject, float *yield,
	     int *distrad, int *diststep, int *distcells,
             int *nmax, float *xstart, float *ystart, float *zstart,
		       int *ibuff,
             float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
             float *mp, float *tdp, float *tcp, float *metalf, int *type,
			float *justburn);

extern "C" void FORTRAN_NAME(star_feedback_pn_snia)
  (int *nx, int *ny, int *nz,
   float *d, float *dm, float *te, float *ge, float *u, float *v,
       float *w, float *metal,
   int *idual, int *imetal, int *imethod, float *dt,
       float *r, float *dx, float *t, float *z,
   float *d1, float *x1, float *v1, float *t1,
       float *sn_param, float *m_eject, float *yield,
   int *distrad, int *diststep, int *distcells,
       int *nmax, float *xstart, float *ystart, float *zstart, int *ibuff,
   float *xp, float *yp, float *zp, float *up, float *vp, float *wp,
       float *mp, float *tdp, float *tcp, float *metalf, int *type,
   float *justburn, int *iPN, int *imetalSNIa, float *metalSNIa);


